- hosts: {{ hosts }}
  become: yes

  tasks:
    - name: start.yaml test
      debug:
        msg: "System {{ inventory_hostname }}"

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - geerlingguy.jenkins
